server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: SJ_JWS_Indv_Inlamning

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/realms/myrealm
          jwk-set-uri: http://127.0.0.1:8080/realms/myrealm/protocol/openid-connect/certs

  datasource:
    url: jdbc:h2:mem:wigellpostDB;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

jwt:
  auth:
    converter:
      resource-id:
        name: myclient
      principle-attribute: preferred_username